name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Download model file
        run: |
            python3 --version
            python3 -m pip install gdown
            cd triton-repository/imagenet-classifier/1
            gdown 1LUetnezvb4W4L_A-tIvmPxp674x_n3ox
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: yashenkoxciv/image-classification-tritonserver:latest